const $=id=>document.getElementById(id);let transactions=JSON.parse(localStorage.getItem('expenseTrackerTransactions')||'[]'),editingId=null;
$('date').value=new Date().toISOString().split('T')[0];
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(n);
const save=()=>localStorage.setItem('expenseTrackerTransactions',JSON.stringify(transactions));
function render(){const income=transactions.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0),expense=transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);$('balance').textContent=money(income-expense);$('income').textContent=money(income);$('expense').textContent=money(expense);$('count').textContent=transactions.length;
 const q=$('search').value.toLowerCase(),ft=$('filterType').value,fc=$('filterCategory').value;const rows=transactions.filter(t=>(t.title.toLowerCase().includes(q)||t.category.toLowerCase().includes(q))&&(ft==='all'||t.type===ft)&&(fc==='all'||t.category===fc)).sort((a,b)=>b.date.localeCompare(a.date));
 $('list').innerHTML=rows.length?rows.map(t=>`<div class="transaction"><div><h3>${safe(t.title)}</h3><p class="meta">${safe(t.category)} • ${t.date}</p></div><div class="right"><div class="amount ${t.type}">${t.type==='income'?'+':'-'}${money(t.amount)}</div><div class="actions"><button class="edit" onclick="editTx('${t.id}')">Edit</button><button class="delete" onclick="deleteTx('${t.id}')">Delete</button></div></div></div>`).join(''):'<p class="empty">No matching transactions.</p>';updateCharts(transactions)}
function safe(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('form').addEventListener('submit',e=>{e.preventDefault();const tx={id:editingId||crypto.randomUUID(),title:$('title').value.trim(),amount:Number($('amount').value),type:$('type').value,category:$('category').value,date:$('date').value};transactions=editingId?transactions.map(t=>t.id===editingId?tx:t):[...transactions,tx];editingId=null;save();e.target.reset();$('date').value=new Date().toISOString().split('T')[0];e.target.querySelector('.primary').textContent='Add Transaction';render()});
window.editTx=id=>{const t=transactions.find(x=>x.id===id);if(!t)return;editingId=id;$('title').value=t.title;$('amount').value=t.amount;$('type').value=t.type;$('category').value=t.category;$('date').value=t.date;$('form').querySelector('.primary').textContent='Update Transaction';$('title').focus()};
window.deleteTx=id=>{transactions=transactions.filter(t=>t.id!==id);save();render()};$('clearAllBtn').onclick=()=>{if(transactions.length&&confirm('Delete all transactions?')){transactions=[];save();render()}};['search','filterType','filterCategory'].forEach(id=>$(id).addEventListener('input',render));render();
